# Generated by Django 5.2.4 on 2025-07-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(choices=[('cyber', 'Cyber Security'), ('net', 'Network Information'), ('soft', 'Software Information')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
